export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';
export const SET_USER_STATUS = 'SET_USER_STATUS';
